### ISSUE TITLE
croppedArea and croppedAreaPixels is returned as NaN on ios portrait

### ISSUE THREAD

**Issue by devnostic** [ValentinH/react-easy-crop#456]
**Describe the bug**
When I am in portrait mode on an iPhone, the cropped pixels come back NaN. I have to turn my phone to landscape mode to get the crop area to show and pixels to generate.

How can I use it in portrait mode?

     <img width="359" alt="Screen Shot 2023-04-12 at 8 42 04 AM" src="https://user-images.githubusercontent.com/55760611/231510376-53a97d46-de58-47ca-975c-d06c7e36ec66.png">

**Comment by devnostic** [comment]
So, after some additional testing, the crop box isn't showing on mobile at the beginning. I have to rotate my phone and then rotate it back in order to get the crop box to work.

Any ideas?

https://user-images.githubusercontent.com/55760611/231513220-171edc9e-750c-4ded-b0f4-7a1b5225ef84.MP4

**Comment by ValentinH** [comment]
The issue doesn't come from the iphone or the portrait mode. It comes from the modal. When the modal is closed and the cropper is rendered, it's not able to compute it's available size.
You should check the existing closed issues with the "modal" keyword.

**Comment by Mustafa-Aswadi** [comment]
Hi @ValentinH 
Have same issue but not in iphone or in portrait mode.
cropArea returns NaN instead of percentages.  
when I open the modal the handleCropComplete calls and after multiple times that I open the modal I get `{x: NaN, y: NaN, width:NaN, height: NaN }` so the cropArea does not apears. and I should close the modal then open it again for appearing the cropArea. 

here is my component for cropping. 


const CropImage = () => {
  const [crop, setCrop] = useState({ x: 0, y: 0 });
  const [zoom, setZoom] = useState(1);
  const [media, setMedia] = useState(null);
  const [croppedArea, setCroppedArea] = useState(null);

  const handleCropComplete = useCallback((croppedArea, _) => {
    console.log('croppedArea', croppedArea);
    setCroppedArea(croppedArea);
  }, []);

  const _handleSetMedia = useCallback((data) => {
    setMedia(data);
  }, []);

  const _handleZoomChange = useCallback((value) => {
    setZoom(value);
  }, []);

  return (
    <Modal
      closeButtonId="crop-image-modal-close-btn"
      onCancel={onCancel}
      visible={visible}
      footer={[
        <Button
          loading={loading}
          onClick={handleSave}
          className="w-[127px]"
          key="modalSave"
          type="primary">
          {t('form.save')}
        </Button>,
      ]}
      bodyStyle={styles.modal}>
      <Space
        className="mt-12 h-[400px] text-center justify-center !min-h-[300px]  w-full"
        direction="vertical">
        <div className="absolute top-14 left-0 right-0 bottom-36">
          <Cropper
            image={src}
            crop={crop}
            zoom={zoom}
            minZoom={1}
            maxZoom={5}
            onCropChange={setCrop}
            aspect={1}
            onCropComplete={handleCropComplete}
            style={styles.cropper}
            setMediaSize={_handleSetMedia}
            onZoomChange={setZoom}
            showGrid={false}
          />
        </div>
        <div className="w-[calc(100%-70px)] !text-left absolute bottom-16 left-10 ">
          <Title level={5} className="ml-1">
            {t('tagPages.zoom')}
          </Title>
          <div className="w-full">
            <Slider
              trackStyle={styles.trackStyle}
              value={zoom}
              min={1}
              max={5}
              step={0.1}
              onChange={_handleZoomChange}
            />
          </div>
        </div>
      </Space>
    </Modal>
  );
};

interface StylesProps {
  trackStyle: CSSProperties;
  modal: CSSProperties;
  cropper: any;
}

const styles: StylesProps = {
  trackStyle: {
    backgroundColor: '#685BC7',
  },
  modal: {
    padding: '0px',
  },
  cropper: {
    cropAreaStyle: {
      borderRadius: '6%',
      border: 'none',
    },
  },
};

export default CropImage;

**Comment by ValentinH** [comment]
You should check the existing closed issues with the "modal" keyword.

**Comment by Mustafa-Aswadi** [comment]
I checked #428, but it does not seems to match my issue. 
my modal does not have any animation.
@ValentinH

**Comment by ValentinH** [comment]
If you can share a codesandbox showing the issue, I'd be happy to help. 🙂

**Comment by Mustafa-Aswadi** [comment]
I am reading the #409 it seems to match my problem. 
If I couldn't find answer I will share codesanbox code for you. 
@ValentinH

**Comment by Mustafa-Aswadi** [comment]
![image](https://github.com/ValentinH/react-easy-crop/assets/93504140/107d5c71-d70d-4036-a10e-7d1c3f1a7118)

![image](https://github.com/ValentinH/react-easy-crop/assets/93504140/71195edf-0281-4bf3-94bb-3ace5237ed9e)

 @ValentinH why I face with the above issue when I pass `initialCroppedAreaPercentages` props

**Comment by ValentinH** [comment]
You are probably passing a different reference at every render. Again, with a codesandbox, I can help.

**Comment by Mustafa-Aswadi** [comment]
@ValentinH  I created an issue for this. #461

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
